spring:
  application:
    name: atcrowdfunding-project
  redis:
    host: 39.97.110.91 #配置阿里云redis的连接

server:
  port: 7000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

