server:
  port: 8761

spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
